env:
  - SOLIDUS_BRANCH=v2.2 DB=postgres
  - SOLIDUS_BRANCH=v2.3 DB=postgres
  - SOLIDUS_BRANCH=v2.4 DB=postgres
  - SOLIDUS_BRANCH=v2.5 DB=postgres
  - SOLIDUS_BRANCH=v2.6 DB=postgres
  - SOLIDUS_BRANCH=master DB=postgres
  - SOLIDUS_BRANCH=v2.2 DB=mysql
  - SOLIDUS_BRANCH=v2.3 DB=mysql
  - SOLIDUS_BRANCH=v2.4 DB=mysql
  - SOLIDUS_BRANCH=v2.5 DB=mysql
  - SOLIDUS_BRANCH=v2.6 DB=mysql
  - SOLIDUS_BRANCH=master DB=mysql

command:
  - bundle && bundle exec rake test_app && bundle exec rspec

